[project]
name = "aws-organizations-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "boto3>=1.38.36",
    "mcp[cli]>=1.9.4",
]
